import { Router } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { User, Doctor, Patient, Appointment, Department, Notification } from '../models/index.js';
import { protect, allow } from '../middleware/auth.js';
import { notify } from '../utils/notify.js';
const router = Router();
const publicUser = u => ({ id: u._id, name: u.name, email: u.email, phone: u.phone, role: u.role, profileImage: u.profileImage });
const tokenFor = u => jwt.sign({ id: u._id, role: u.role }, process.env.JWT_SECRET, { expiresIn: '7d' });
const asyncRoute = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next);

router.post('/auth/register', asyncRoute(async (req,res) => {
  const parsed = z.object({ name:z.string().min(2), email:z.string().email(), password:z.string().min(8), phone:z.string().optional(), role:z.enum(['patient','doctor']).default('patient') }).safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0].message });
  const data=parsed.data; if(await User.exists({email:data.email.toLowerCase()})) return res.status(409).json({message:'An account with this email already exists.'});
  const user=await User.create({...data,password:await bcrypt.hash(data.password,12)});
  if(user.role==='patient') await Patient.create({userId:user._id});
  if(user.role==='doctor') await Doctor.create({userId:user._id,specialization:req.body.specialization||'General Medicine',qualification:req.body.qualification||'',status:'pending'});
  res.status(201).json({token:tokenFor(user),user:publicUser(user)});
}));
router.post('/auth/login', asyncRoute(async(req,res)=>{const user=await User.findOne({email:String(req.body.email||'').toLowerCase()}).select('+password'); if(!user||!await bcrypt.compare(req.body.password||'',user.password)) return res.status(401).json({message:'Email or password is incorrect.'}); if(!user.active)return res.status(403).json({message:'This account has been deactivated.'}); res.json({token:tokenFor(user),user:publicUser(user)});}));
router.get('/auth/me',protect,(req,res)=>res.json({user:publicUser(req.user)}));
router.put('/auth/me',protect,asyncRoute(async(req,res)=>{const fields=['name','phone','profileImage']; for(const f of fields) if(req.body[f]!==undefined)req.user[f]=req.body[f]; await req.user.save(); if(req.user.role==='patient')await Patient.findOneAndUpdate({userId:req.user._id},{$set:{dateOfBirth:req.body.dateOfBirth,gender:req.body.gender,address:req.body.address}},{upsert:true});res.json({user:publicUser(req.user)});}));

router.get('/doctors',asyncRoute(async(req,res)=>{const q={status:'approved'};if(req.query.specialization)q.specialization=new RegExp(String(req.query.specialization),'i');if(req.query.department)q.department=new RegExp(String(req.query.department),'i');if(req.query.available==='true')q.isAvailable=true;let docs=await Doctor.find(q).populate('userId','name email profileImage');if(req.query.search){const s=String(req.query.search).toLowerCase();docs=docs.filter(d=>d.userId?.name.toLowerCase().includes(s)||d.specialization.toLowerCase().includes(s));}res.json({doctors:docs});}));
router.get('/doctors/:id',asyncRoute(async(req,res)=>{const d=await Doctor.findById(req.params.id).populate('userId','name email phone profileImage');if(!d)return res.status(404).json({message:'Doctor not found.'});res.json({doctor:d});}));
router.get('/doctors/:id/availability',asyncRoute(async(req,res)=>{const d=await Doctor.findById(req.params.id);if(!d)return res.status(404).json({message:'Doctor not found.'});const date=new Date(`${req.query.date}T00:00:00`);if(!req.query.date||Number.isNaN(+date))return res.status(400).json({message:'Choose a valid date.'});const slots=[];const windows=d.availability.filter(a=>a.day===date.getDay());for(const w of windows){let [h,m]=w.start.split(':').map(Number),[eh,em]=w.end.split(':').map(Number);for(let t=h*60+m;t+d.slotDuration<=eh*60+em;t+=d.slotDuration){const hh=String(Math.floor(t/60)).padStart(2,'0'),mm=String(t%60).padStart(2,'0'),time=`${hh}:${mm}`;const inBreak=(w.breaks||[]).some(b=>time>=b.start&&time<b.end);slots.push({time,available:!inBreak&&d.isAvailable&&!d.blockedDates.some(x=>new Date(x).toDateString()===date.toDateString())});}}const booked=await Appointment.find({doctorId:d._id,date:{$gte:date,$lt:new Date(+date+86400000)},status:{$nin:['Cancelled']}}).select('time');const taken=new Set(booked.map(a=>a.time));const now=new Date();res.json({slots:slots.map(s=>({...s,available:s.available&&!taken.has(s.time)&&(+date>new Date(now.getFullYear(),now.getMonth(),now.getDate())||(+date===new Date(now.getFullYear(),now.getMonth(),now.getDate())&&s.time>`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`))}))});}));
router.put('/doctors/:id/availability',protect,allow('doctor','admin'),asyncRoute(async(req,res)=>{let d=await Doctor.findById(req.params.id);if(!d)return res.status(404).json({message:'Doctor not found.'});if(req.user.role==='doctor'&&String(d.userId)!==String(req.user._id))return res.status(403).json({message:'You can only update your own availability.'});d.availability=req.body.availability||d.availability;d.slotDuration=req.body.slotDuration||d.slotDuration;d.isAvailable=req.body.isAvailable??d.isAvailable;d.blockedDates=req.body.blockedDates||d.blockedDates;await d.save();res.json({doctor:d});}));
router.post('/appointments',protect,allow('patient'),asyncRoute(async(req,res)=>{const {doctorId,date,time,reason,notes}=req.body;const day=new Date(`${date}T00:00:00`);if(!doctorId||!date||!time||!reason?.trim()||Number.isNaN(+day))return res.status(400).json({message:'Please provide a doctor, date, time, and reason for your visit.'});if(+day<new Date(new Date().toDateString()))return res.status(400).json({message:'Appointments must be booked for a future date.'});const d=await Doctor.findById(doctorId).populate('userId','name');if(!d||d.status!=='approved'||!d.isAvailable)return res.status(400).json({message:'This doctor is currently unavailable.'});const daySlots=d.availability.filter(a=>a.day===day.getDay());if(!daySlots.some(w=>time>=w.start&&time<w.end&&!(w.breaks||[]).some(b=>time>=b.start&&time<b.end))||d.blockedDates.some(x=>new Date(x).toDateString()===day.toDateString()))return res.status(400).json({message:'This doctor is not available at the selected time.'});try{const slotKey=`${d._id}:${day.toISOString().slice(0,10)}:${time}`;const appt=await Appointment.create({patientId:req.user._id,doctorId:d._id,date:day,time,slotKey,reason:reason.trim(),notes});const doc=await appt.populate([{path:'doctorId',populate:{path:'userId',select:'name'}},{path:'patientId',select:'name email'}]);await notify(d.userId._id,'New appointment booked',`${req.user.name} booked an appointment for ${date} at ${time}.`);await notify(req.user._id,'Appointment request received',`Your appointment with ${d.userId.name} is pending confirmation.`);return res.status(201).json({appointment:doc});}catch(e){if(e.code===11000)return res.status(409).json({message:'This appointment slot is no longer available. Please select another time.'});throw e;}}));
router.get('/appointments',protect,asyncRoute(async(req,res)=>{let q={};if(req.user.role==='patient')q.patientId=req.user._id;else if(req.user.role==='doctor'){const d=await Doctor.findOne({userId:req.user._id});q.doctorId=d?._id||null;}if(req.query.status)q.status=req.query.status;const appointments=await Appointment.find(q).sort({date:1,time:1}).populate('patientId','name email phone').populate({path:'doctorId',populate:{path:'userId',select:'name'}});res.json({appointments});}));
router.get('/appointments/:id',protect,asyncRoute(async(req,res)=>{const a=await Appointment.findById(req.params.id).populate('patientId','name email phone').populate({path:'doctorId',populate:{path:'userId',select:'name'}});if(!a)return res.status(404).json({message:'Appointment not found.'});const d=a.doctorId;const owner=String(a.patientId._id)===String(req.user._id)||String(d?.userId?._id)===String(req.user._id);if(!owner&&req.user.role!=='admin')return res.status(403).json({message:'You do not have access to this appointment.'});res.json({appointment:a});}));
router.patch('/appointments/:id',protect,asyncRoute(async(req,res)=>{const a=await Appointment.findById(req.params.id).populate('patientId','name').populate({path:'doctorId',populate:{path:'userId',select:'name'}});if(!a)return res.status(404).json({message:'Appointment not found.'});const isPatient=String(a.patientId._id)===String(req.user._id),isDoctor=String(a.doctorId?.userId?._id)===String(req.user._id),isAdmin=req.user.role==='admin';if(!isPatient&&!isDoctor&&!isAdmin)return res.status(403).json({message:'You do not have access to this appointment.'});const status=req.body.status;if(status==='Cancelled'){if(['Completed','Cancelled'].includes(a.status))return res.status(400).json({message:'This appointment can no longer be cancelled.'});a.status='Cancelled';a.slotKey=undefined;}else if(status==='Confirmed'&&(isDoctor||isAdmin))a.status=status;else if(status==='Completed'&&(isDoctor||isAdmin))a.status=status;else if(status==='No-Show'&&(isDoctor||isAdmin))a.status=status;else if(req.body.date&&req.body.time){const day=new Date(`${req.body.date}T00:00:00`);if(Number.isNaN(+day)||+day<new Date(new Date().toDateString()))return res.status(400).json({message:'Choose a future date.'});const d=await Doctor.findById(a.doctorId._id);const windows=d.availability.filter(w=>w.day===day.getDay());if(!d.isAvailable||d.blockedDates.some(x=>new Date(x).toDateString()===day.toDateString())||!windows.some(w=>req.body.time>=w.start&&req.body.time<w.end&&!(w.breaks||[]).some(b=>req.body.time>=b.start&&req.body.time<b.end)))return res.status(400).json({message:'This doctor is not available at the selected time.'});const key=`${d._id}:${day.toISOString().slice(0,10)}:${req.body.time}`;const exists=await Appointment.exists({slotKey:key,_id:{$ne:a._id}});if(exists)return res.status(409).json({message:'This appointment slot is no longer available.'});a.date=day;a.time=req.body.time;a.slotKey=key;a.status='Rescheduled';}else return res.status(400).json({message:'Choose a valid appointment action.'});await a.save();const message=`Appointment ${a.status.toLowerCase()} for ${a.date.toISOString().slice(0,10)} at ${a.time}.`;await notify(a.patientId._id,'Appointment updated',message);await notify(a.doctorId.userId._id,'Appointment updated',message);res.json({appointment:a});}));
router.delete('/appointments/:id',protect,asyncRoute(async(req,res)=>{const a=await Appointment.findById(req.params.id).populate('doctorId');if(!a)return res.status(404).json({message:'Appointment not found.'});const isPatient=String(a.patientId)===String(req.user._id),isDoctor=String(a.doctorId?.userId)===String(req.user._id);if(!isPatient&&!isDoctor&&req.user.role!=='admin')return res.status(403).json({message:'You do not have access to this appointment.'});if(['Completed','Cancelled'].includes(a.status))return res.status(400).json({message:'This appointment can no longer be cancelled.'});a.status='Cancelled';a.slotKey=undefined;await a.save();await notify(a.patientId,'Appointment cancelled',`Your appointment on ${a.date.toISOString().slice(0,10)} at ${a.time} was cancelled.`);await notify(a.doctorId.userId,'Appointment cancelled',`An appointment for ${a.date.toISOString().slice(0,10)} at ${a.time} was cancelled.`);res.json({appointment:a});}));

router.get('/notifications',protect,asyncRoute(async(req,res)=>res.json({notifications:await Notification.find({userId:req.user._id}).sort({createdAt:-1}).limit(40)})));
router.patch('/notifications/:id/read',protect,asyncRoute(async(req,res)=>{const n=await Notification.findOneAndUpdate({_id:req.params.id,userId:req.user._id},{isRead:true},{new:true});res.json({notification:n});}));
router.get('/departments',asyncRoute(async(req,res)=>res.json({departments:await Department.find().sort('name')})));
router.get('/admin/overview',protect,allow('admin'),asyncRoute(async(req,res)=>{const [patients,doctors,appointments,pending,completed,cancelled,today]=await Promise.all([User.countDocuments({role:'patient'}),Doctor.countDocuments(),Appointment.countDocuments(),Appointment.countDocuments({status:'Pending'}),Appointment.countDocuments({status:'Completed'}),Appointment.countDocuments({status:'Cancelled'}),Appointment.countDocuments({date:{$gte:new Date(new Date().toDateString()),$lt:new Date(+new Date(new Date().toDateString())+86400000)}})]);res.json({stats:{patients,doctors,appointments,pending,completed,cancelled,today}});}));
router.get('/admin/users',protect,allow('admin'),asyncRoute(async(req,res)=>{const role=req.query.role;res.json({users:await User.find(role?{role}:{}).sort({createdAt:-1}).select('-password')});}));
router.patch('/admin/users/:id',protect,allow('admin'),asyncRoute(async(req,res)=>{const u=await User.findByIdAndUpdate(req.params.id,{active:req.body.active},{new:true}).select('-password');if(!u)return res.status(404).json({message:'User not found.'});res.json({user:u});}));
router.get('/admin/doctors',protect,allow('admin'),asyncRoute(async(req,res)=>res.json({doctors:await Doctor.find().populate('userId','name email active').sort({createdAt:-1})})));
router.patch('/admin/doctors/:id',protect,allow('admin'),asyncRoute(async(req,res)=>{const d=await Doctor.findById(req.params.id);if(!d)return res.status(404).json({message:'Doctor not found.'});for(const key of ['specialization','department','qualification','experience','bio','consultationFee','status','availability','slotDuration','isAvailable'])if(req.body[key]!==undefined)d[key]=req.body[key];await d.save();res.json({doctor:d});}));
router.post('/admin/doctors',protect,allow('admin'),asyncRoute(async(req,res)=>{const {name,email,password,specialization,qualification,department}=req.body;if(!name||!email||!password||!specialization)return res.status(400).json({message:'Name, email, password, and specialization are required.'});if(await User.exists({email:email.toLowerCase()}))return res.status(409).json({message:'An account with this email already exists.'});const user=await User.create({name,email,password:await bcrypt.hash(password,12),role:'doctor'});const doctor=await Doctor.create({userId:user._id,specialization,qualification,department,status:'approved'});res.status(201).json({doctor:await doctor.populate('userId','name email')});}));
router.get('/admin/appointments',protect,allow('admin'),asyncRoute(async(req,res)=>res.json({appointments:await Appointment.find(req.query.status?{status:req.query.status}:{}).sort({date:-1}).populate('patientId','name email').populate({path:'doctorId',populate:{path:'userId',select:'name'}})})));
router.post('/admin/departments',protect,allow('admin'),asyncRoute(async(req,res)=>{const department=await Department.create({name:req.body.name,description:req.body.description});res.status(201).json({department});}));
export default router;
